# .github/workflows/pelican-deploy.yml
name: Build and Deploy Pelican Site

on:
  pull_request:
    branches:
      - master
      - main
  push:
    branches:
      - master
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      TZ: America/New_York
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies from requirements.txt
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Build the Pelican site
        run: pelican content -o output -s publishconf.py
      - name: Remove .webassets-cache directory
        run: rm -rf output/theme/.webassets-cache
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: output
